### ISSUE TITLE
feat: Contract Architecture 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/cairo-ecs#1]
## Initial Architecture of the ECS system

Comment/pseudo code Architecture for review. This will be complete once general consensus is formed around the structure.

- [ ] Contracts (World.cairo, Component.cairo, System.cairo)
- [ ] Key events and functions
- [ ] Preliminary Namespace structure

High-level goals:
- Only one contract emits events
- Strictly typed generalized components
