### ISSUE TITLE
feat: Authentication & Ownership throughout the world

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/cairo-ecs#4]
An Authentication pattern is required within the ECS. A simple pattern will suffice for v0.1

Systems.cairo
- [ ] Check caller is Approved to call System. Systems can call one another.
- [ ] Check caller is Owner

Components.cairo
- [ ] Check caller is approved System only. Components can only be called by Systems.
